#dbconfig

[DbName] 
Server = "127.0.0.1"        #localhost
Port = 3306                 #1433
User = "user"               #your_db_username
Password = "pass"           #your_secure_password
Database = "dbname"         #your_database_name
DBType = "mysql"            # or "mysql", "postgres", etc.

[DBConnectionPool]
DbConMaxIdleTime=3
DbConMaxOpenConns=3
DbConMaxIdleConns=3